### ISSUE TITLE
dotWidget isn't defined

### ISSUE THREAD

**Issue by 1Krishna16** [rajnishsharma1/another_stepper#16]
I am having trouble using `dotWidget`.
![image](https://user-images.githubusercontent.com/50993917/219347185-b4168b52-9fdd-468e-a837-3d0ea7e899cb.png)
![image](https://user-images.githubusercontent.com/50993917/219347524-b44ba866-542a-45d3-82f8-009ea7d3536a.png)

Official Code:
![image](https://user-images.githubusercontent.com/50993917/219348010-0c20c935-2cd3-447d-9eb4-5a3723fae239.png)

I am using ^1.2.0 version
![image](https://user-images.githubusercontent.com/50993917/219347281-1e17ba78-ef2a-41e7-8dbb-085a11461b90.png)

What i want to achieve ? 

![image](https://user-images.githubusercontent.com/50993917/219348362-9f170e25-f7de-4b11-b038-854e59a5d447.png)
I want to achieve this, when the active link is 3 the first 3 steps should be green icon, while the 4th should be grey, 
Presently i am not able to achieve this dynamicity. I have to either hardcode the iconWidget in the Stepper which will not help me change it dynamically. How to achieve the above stepper from the official docs.

**Comment by iamtechmanish** [comment]
refer to this : https://github.com/rajnishsharma1/another_stepper/issues/14#issuecomment-1404062824

**Comment by rajnishsharma1** [comment]
Hey @1Krishna16  we have deprecated the `dotWidget` . Now you can pass the `dotWidget` properties in `StepperData() `only, you can find that property by name `iconWidget`.

**Comment by krishnaacharya-official** [comment]
> refer to this : [#14 (comment)](https://github.com/rajnishsharma1/another_stepper/issues/14#issuecomment-1404062824)
But i have the same problem as in https://github.com/rajnishsharma1/another_stepper/issues/14#issuecomment-1404696760
How to change the color of icon based on the active index as shown in the image of https://github.com/rajnishsharma1/another_stepper/issues/16#issue-1587470561


How to achieve this functionality now ?

**Comment by krishnaacharya-official** [comment]
Thank you but could you possibly give a running example of the same. So that this issue can be considered solved.

**Comment by rajnishsharma1** [comment]
Please check https://github.com/rajnishsharma1/another_stepper/issues/14#issuecomment-1433247043

@sampaiopedrodev has mentioned the working solution!!
